# Gradle
org.gradle.caching=true
org.gradle.caching.debug=false
org.gradle.configureondemand=true
org.gradle.parallel=true
org.gradle.jvmargs=-Xmx2048M -Dfile.encoding=UTF-8
org.gradle.logging.stacktrace=full

# Kotlin
kotlin.caching.enabled=true
kotlin.incremental=true
kotlin.stdlib.default.dependency=false

# Maven Credentials
mavenUser=
mavenPassword=
