name: FunnyGuilds
main: net.dzikoysk.funnyguilds.FunnyGuilds
version: '${project.version} Tribute-${git.commit.id.abbrev}'
author: 'FunnyGuilds Team'
website: https://github.com/FunnyGuilds
softdepend: [WorldEdit, WorldGuard, Vault, PlaceholderAPI, FunnyTab, BungeeTabListPlus, MVdWPlaceholderAPI]
loadbefore: [WorldGuard]
api-version: 1.13

permissions:
  funnyguilds.*:
    default: op
    children:
      funnyguilds.player: true
      funnyguilds.vip: true
      funnyguilds.admin: true

  funnyguilds.admin:
    default: op
    children:
      funnyguilds.reload: true
      funnyguilds.admin.build: true
      funnyguilds.admin.interact: true
      funnyguilds.admin.notification: true
      funnyguilds.admin.disabledummy: false

  funnyguilds.vip:
    default: op
    children:
      funnyguilds.vip.items: true
      funnyguilds.vip.rank: true
      funnyguilds.vip.base: true
      funnyguilds.vip.baseTeleportTime: true

  funnyguilds.player:
    default: true
    children:
      funnyguilds.ally: true
      funnyguilds.base: true
      funnyguilds.break: true
      funnyguilds.create: true
      funnyguilds.delete: true
      funnyguilds.invite: true
      funnyguilds.join: true
      funnyguilds.leave: true
      funnyguilds.kick: true
      funnyguilds.enlarge: true
      funnyguilds.help: true
      funnyguilds.info: true
      funnyguilds.top: true
      funnyguilds.validity: true
      funnyguilds.leader: true
      funnyguilds.deputy: true
      funnyguilds.ranking: true
      funnyguilds.items: true
      funnyguilds.escape: true
      funnyguilds.rankreset: true
      funnyguilds.manage: true