name: FunnyGuilds CI
on:
  push:
    branches: [ 4.x, 5.x, 6.x ]
  pull_request:
    branches: [ 4.x, 5.x, 6.x ]

permissions:
  pull-requests: write
  issues: write
  
jobs:
  build:
    name: "Build with JDK${{ matrix.jdk }}"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        jdk: [ 21 ]
    steps:
      - name: Find comment with artifact link
        uses: peter-evans/find-comment@v3
        if: github.event_name == 'pull_request'
        id: init-find-comment
        continue-on-error: true
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
      - name: Create initial comment for artifact link
        uses: peter-evans/create-or-update-comment@v4
        id: create-comment
        continue-on-error: true
        if: |
          github.event_name == 'pull_request' &&
          steps.init-find-comment.outputs.comment-id == ''
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ### 📦 Dev Build

            ⏳ Tutaj dostępna będzie testowa wersja **FunnyGuilds**, posiadająca zmiany z tego Pull Requesta.
          edit-mode: replace
          
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.jdk }}
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-read-only: ${{ github.ref != 'refs/heads/4.x' && github.ref != 'refs/heads/5.x' && github.ref != 'refs/heads/6.x' }}
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build FunnyGuilds
        run: ./gradlew build --stacktrace -i
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        id: upload-artifact
        continue-on-error: true
        with:
          name: FunnyGuilds Dev Build
          path: plugin/build/libs/FunnyGuilds*.jar
          retention-days: 30
          overwrite: true
          
      - name: Find comment with artifact link
        uses: peter-evans/find-comment@v3
        if: github.event_name == 'pull_request'
        id: find-comment
        continue-on-error: true
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
      - name: Update comment with artifact link
        uses: peter-evans/create-or-update-comment@v4
        if: github.event_name == 'pull_request'
        continue-on-error: true
        with:
          comment-id: ${{ steps.find-comment.outputs.comment-id }}
          body: |
            ### 📦 Dev Build
            
            Możesz pobrać testową wersję **FunnyGuilds**, ze zmianami z tego Pull Requesta [tutaj](${{ steps.upload-artifact.outputs.artifact-url }})
            
            **⚠️ Uwaga!** Jest to wersja testowa, nie powinno się jej używać na serwerze produkcyjnym. Może posiadać 
            błędy mogące powodować utratę danych graczy i gildii, konfiguracji pluginu itp.
          edit-mode: replace
          reactions: rocket
