name: Publish FunnyGuilds to Panda repository
on:
  push:
    branches: [ 4.x, 5.x, 6.x ]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - uses: burrunan/gradle-cache-action@v2
        name: Publish FunnyGuilds
        with:
          arguments: clean build :plugin:publish --stacktrace
        env:
          MAVEN_NAME: ${{ secrets.MAVEN_NAME }}
          MAVEN_TOKEN: ${{ secrets.MAVEN_TOKEN }}
